### ISSUE TITLE
Not working in 1.7.10 (+Thermos Exception)

### ISSUE THREAD

**Issue by Danielxs01** [Danielxs01/SimpleBlockLogging#1]
2 Fehler:
 1. Actionbar -> NoSuchMethodError
    

`Caused by: java.lang.NoSuchMethodError: org.bukkit.entity.Player$Spigot.sendMessage(Lnet/md_5/bungee/api/ChatMessageType;[Lnet/md_5/bungee/api/chat/BaseComponent;)V `

 2. Speichern der blocks.yml

`java.lang.NullPointerException: Nodes must be provided.`

**Comment by Danielxs01** [comment]
Gefixt.
Actionbar: Entweder wird die BarAPI (falls vorhanden) vewendet oder die Nachricht steht im Chat.
Config: Registrieren des Konfigobjekts von onEnable() to onLoad() verschoben.
